_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 1
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.9
            "8":
                - 1
                - 5
            "12": 0.19.9
            "13": linux-x86_64
base_channels:
    value: 64
batch_size:
    value: 4
bce_weight:
    value: 0.5
bilinear:
    value: true
dice_weight:
    value: 1
epochs:
    value: 30
focal_weight:
    value: 0.5
image_size:
    value: 512
iou_weight:
    value: 0
learning_rate:
    value: 0.0001
loss_function:
    value: CombinedLoss
model_type:
    value: UNet
optimizer:
    value: Adam
scheduler:
    value: ReduceLROnPlateau
